eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9010/eureka/}
logging:
  level:
    root: INFO
    org:
      springframework.web: ERROR
      hibernate: ERROR
      apache:
        kafka: ERROR
    com:
      assetmark: INFO     
spring:
  zipkin:
    enabled: false
  sleuth:
    enabled: false
  jackson:
    time-zone: Asia/Kolkata
  data:
    mongodb:
      host: localhost
management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  health:
    probes:
      enabled: true  
    binders:
      enabled: true  
